@startuml UseradminSequence

skinparam responseMessageBelowArrow true
skinparam SequenceMessageAlignment center

actor admin as admin #OliveDrab

entity Post as Post #LightYellow
entity Comment as Comment #LightYellow

database 2dbubbleas 2dbubble#YellowGreen

admin -> 2dbubbles: créer un compte
alt cas réussi
2dbubble-> admin: valider création du compte
else email déjà existant 
2dbubble-> admin: échec de l'inscription

admin  -> 2dbubbles: demander authentification 
2dbubble-> admin: valider authentification 
else identification invalides
2dbubble-> admin: échec de l'authentification

admin  -> Post: ajouter post
Post -> admin: valider ajout
else le titre ne peut être nul
Post -> admin: échec de l'ajout

admin  -> Post: éditer post
Post -> admin: valider édition
else ce post n'existe pas
Post -> admin: le post recherché n'existe pas

admin  -> Post: supprimer post
else erreur 403
Post -> admin: vous n'avez pas accès à cette ressource

admin  -> Comment: modérer commentaitre
Comment -> admin: accepter commentaitre
admin  -> Comment: refuser commentaitre
Comment -> admin: supprimer commentaitre

end
@enduml