@startuml UserSuperadminSequence

skinparam responseMessageBelowArrow true
skinparam SequenceMessageAlignment center

actor Superadmin as Superadmin #DarkOliveGreen

entity Post as Post #LightYellow
entity Comment as Comment #LightYellow

database 2dbubbles as 2dbubbles #HotPink

Superadmin -> 2dbubbles: créer un compte
alt cas réussi
2dbubbles-> Superadmin: valider création du compte
else email déjà existant 
2dbubbles-> Superadmin: échec de l'inscription

Superadmin -> 2dbubbles: demander authentification 
2dbubbles-> Superadmin: valider authentification 
else identification invalides
2dbubbles-> Superadmin: échec de l'authentification

Superadmin -> Post: ajouter post
Post -> Superadmin: valider ajout
else le champ titre ne peut pas être vide
Post -> Superadmin: échec de l'ajout

Superadmin -> Post: éditer post
Post -> Superadmin: valider édition
else ce post n'existe pas
Post -> Superadmin: le post en cours de modification n'existe pas

Superadmin -> Post: supprimer post
Post -> Superadmin: valider suppression

Superadmin -> Comment: modérer commentaire
Comment -> Superadmin: accepter commentaire
Superadmin  -> Comment: refuser commentaire
Comment -> Superadmin: supprimer commentaire

end
@enduml