@startuml UserSuperAdminSequence

skinparam responseMessageBelowArrow true
skinparam SequenceMessageAlignment center

actor SuperAdmin as SuperAdmin #DarkOliveGreen

entity Post as Post #LightYellow
entity Comment as Comment #LightYellow

database 2dbubbles as 2dbubbles #YellowGreen

SuperAdmin -> 2dbubbles: créer un compte
alt cas réussi
2dbubbles -> SuperAdmin: valider création du compte
else email déjà existant 
2dbubbles -> SuperAdmin: échec de l'inscription

SuperAdmin -> 2dbubbles: demander authentification 
2dbubbles -> SuperAdmin: valider authentification 
else identification invalides
2dbubbles -> SuperAdmin: échec de l'authentification

SuperAdmin -> Post: ajouter post
Post -> SuperAdmin: valider ajout
else le titre ne peut être nul
Post -> SuperAdmin: échec de l'ajout

SuperAdmin -> Post: éditer post
Post -> SuperAdmin: valider édition
else ce post n'existe pas
Post -> SuperAdmin: le post recherché n'existe pas

SuperAdmin -> Post: supprimer post
Post -> SuperAdmin: valider suppression

SuperAdmin -> Comment: modérer commentaitre
Comment -> SuperAdmin: accepter commentaitre
SuperAdmin  -> Comment: refuser commentaitre
Comment -> SuperAdmin: supprimer commentaitre

end
@enduml