@startuml UserSequence

skinparam responseMessageBelowArrow true
skinparam SequenceMessageAlignment center

actor User as User #Plum

entity Post as Post #LightYellow
entity Comment as Comment #LightYellow
entity Admin as Admin #LightYellow

database 2dbubbles as 2dbubbles #HotPink

User -> 2dbubbles: créer un compte
alt cas réussi
2dbubbles-> User: valider création du compte
else email déjà existant 
2dbubbles-> User: échec de l'inscription

User -> 2dbubbles: demander authentification 
2dbubbles-> User: valider authentification 
else identification invalides
2dbubbles-> User: échec de l'authentification


User -> Comment: ajouter commentaire
Comment -> User: commentaitre en attente de validation
else commentaire invalide
User -> Admin: refuser commentaire
Admin -> User: commentaire refusé supprimé

User -> Comment: consulter tous ses commentaires
Comment -> User: afficher liste de ses commentaires

2dbubbles -> User: envoie du formulaire de contact
2dbubbles -> User: formulaire de contact envoyé
else il y a des erreurs sur le formulaire
User -> Comment: le champ email vide 

end
@enduml