
@startuml admin

left to right direction

actor "admin" as admin #OliveDrab

rectangle 2dbubble{
  usecase "Créer un compte" as UC1
  usecase "Se connecter" as UC2
  usecase "Ajouter des posts" as UC3
  usecase "Modifier les posts" as UC4
  usecase "Afficher les posts" as UC5
  usecase "Ajouter des commentaires" as UC6
}

admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
admin --> UC5
admin --> UC6

@enduml
