
@startuml Superadmin

left to right direction

actor "Superadmin" as Superadmin #OliveDrab

rectangle 2dbubble{
  usecase "Créer un compte" as UC1
  usecase "Se connecter" as UC2
  usecase "Ajouter des posts" as UC3
  usecase "Modifier des posts" as UC4
  usecase "Supprimer des posts" as UC5
  usecase "Afficher les posts" as UC6
  usecase "Ajouter des commentaires" as UC7
  usecase "Modérer des commentaires" as UC8
  usecase "Supprimer des commentaires" as UC9
}

Superadmin --> UC1
Superadmin --> UC2
Superadmin --> UC3
Superadmin --> UC4
Superadmin --> UC5
Superadmin --> UC6
Superadmin --> UC7
Superadmin --> UC8
Superadmin --> UC9

@enduml
