@startuml User

left to right direction

actor "User" as User #Plum

rectangle 2dbubbles{
  usecase "S'inscrire" as UC1
  usecase "Se connecter" as UC2
  usecase "Vouloir Consulter les posts" as UC3
  usecase "Ajouter ses commentaires" as UC4
  usecase "Modifier ses commentaires" as UC5
  usecase "Supprimer ses commentaires" as UC6
  usecase "Contacter l'administrateur du blog" as UC7
  usecase "Consutler d'autre ressource du blog" as UC8
  usecase "Télécharger le CV" as UC9
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6
User --> UC7
User --> UC8
User --> UC9

@enduml