@startuml admin

left to right direction

actor "admin" as admin #OliveDrab

rectangle 2dbubbles{
  usecase "Créer un compte" as UC1
  usecase "Se connecter" as UC2
  usecase "Lire les posts" as UC3
  usecase "Ajouter ses commentaires" as UC4
  usecase "Modifier ses commentaires" as UC5
  usecase "Modérer des commentaires" as UC6
  usecase "Supprimer des commentaires" as UC7
}

admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
admin --> UC5
admin --> UC6
admin --> UC7

@enduml